"""Generate tests/data/strict_domain_fixture.gdx.

A minimal GDX with a parent Set and a strict-domain subset. Used by
tests/test_domain.py::test_read_external_strict_fixture to validate that
gdxpds can read strict-domain (code 3 from gdxSymbolGetDomainX) files.

A more rigorous version of this fixture would be generated by GAMS
itself (a short .gms file invoking the GAMS compiler), since the current
generator uses gdxpds's own write path — so a bug there would not be
caught by the read-back test alone. Replace this script's body if/when
that fixture becomes available.

Usage (from repo root, with the venv active and $env:GAMS_DIR set):

    python dev\\build_strict_domain_fixture.py
"""

import os

import pandas as pd

import gdxpds.gdx

OUT_PATH = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "tests",
        "data",
        "strict_domain_fixture.gdx",
    )
)


def main():
    # Pin the gdxcc oracle so the committed fixture is written deterministically
    # regardless of any ambient GDXPDS_BACKEND.
    with gdxpds.gdx.GdxFile(backend="gdxcc") as gdx:
        gdx.append(gdxpds.gdx.GdxSymbol("t", gdxpds.gdx.GamsDataType.Set, dims=["t"]))
        gdx[-1].dataframe = pd.DataFrame(
            [["a", True], ["b", True], ["c", True]], columns=["t", "Value"]
        )

        gdx.append(
            gdxpds.gdx.GdxSymbol(
                "sub_t", gdxpds.gdx.GamsDataType.Set, dims=["t"], domain=[gdx["t"]]
            )
        )
        gdx[-1].dataframe = pd.DataFrame([["a", True], ["c", True]], columns=["t", "Value"])

        os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
        gdx.write(OUT_PATH)

    print(f"Wrote {OUT_PATH} ({os.path.getsize(OUT_PATH)} bytes)")


if __name__ == "__main__":
    main()
